name: CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            lib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v3
        with:
          pyvista: false
      - uses: taiki-e/install-action@just
      - run: just test

  package:
    name: Package
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            lib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: taiki-e/install-action@just
      - run: just package
      - uses: actions/upload-artifact@v3
        with:
          name: packaged-game
          path: packaged
